TARGET_NAME = stm32f071xb

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F071xB
TARGET_LDFLAGS = -Tstm32f071xb.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f071xb.s

include ../../Makefile.common
