TARGET_NAME = stm32f030x8

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F030x8
TARGET_LDFLAGS = -Tstm32f030x8.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f030x8.s

include ../../Makefile.common
