TARGET_NAME = stm32f091xc

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F091xC
TARGET_LDFLAGS = -Tstm32f091xc.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f091xc.s

include ../../Makefile.common
