TARGET_NAME = stm32f078xx

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F078xx
TARGET_LDFLAGS = -Tstm32f078xx.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f078xx.s

include ../../Makefile.common
