TARGET_NAME = stm32f048xx

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F048xx
TARGET_LDFLAGS = -Tstm32f048xx.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f048xx.s

include ../../Makefile.common
