TARGET_NAME = stm32f072xb

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F072xB
TARGET_LDFLAGS = -Tstm32f072xb.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f072xb.s

include ../../Makefile.common
