TARGET_NAME = stm32f038xx

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F038xx
TARGET_LDFLAGS = -Tstm32f038xx.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f038xx.s

include ../../Makefile.common
