TARGET_NAME = stm32f051x8

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F051x8
TARGET_LDFLAGS = -Tstm32f051x8.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f051x8.s

include ../../Makefile.common
