TARGET_NAME = stm32f070x6

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F070x6
TARGET_LDFLAGS = -Tstm32f070x6.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f070x6.s

include ../../Makefile.common
