TARGET_NAME = stm32f058xx

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F058xx
TARGET_LDFLAGS = -Tstm32f058xx.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f058xx.s

include ../../Makefile.common
