TARGET_NAME = stm32f098xx

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F098xx
TARGET_LDFLAGS = -Tstm32f098xx.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f098xx.s

include ../../Makefile.common
