TARGET_NAME = stm32f070xb

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F070xB
TARGET_LDFLAGS = -Tstm32f070xb.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f070xb.s

include ../../Makefile.common
