TARGET_NAME = stm32f042x6

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F042x6
TARGET_LDFLAGS = -Tstm32f042x6.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f042x6.s

include ../../Makefile.common
