TARGET_NAME = stm32f031x6

TARGET_ASFLAGS =
TARGET_CFLAGS = -DSTM32F031x6
TARGET_LDFLAGS = -Tstm32f031x6.ld

TARGET_SRC_ROOT = $(shell pwd)/src
TARGET_SRC_FILES = \
	$(TARGET_SRC_ROOT)/startup_stm32f031x6.s

include ../../Makefile.common
